#if WINE_ASAN
void __asan_poison_memory_region(void const volatile *addr, SIZE_T size);
void __asan_unpoison_memory_region(void const volatile *addr, SIZE_T size);
void __asan_poison_stack_memory(void const volatile *addr, SIZE_T size);
void __asan_unpoison_stack_memory(void const volatile *addr, SIZE_T size);
int __asan_address_is_poisoned(void const volatile *addr);
void *__asan_region_is_poisoned(void *beg, SIZE_T size);
void __asan_describe_address(void *addr);
int __asan_report_present(void);
void *__asan_get_report_pc(void);
void *__asan_get_report_bp(void);
void *__asan_get_report_sp(void);
void *__asan_get_report_address(void);
int __asan_get_report_access_type(void);
SIZE_T __asan_get_report_access_size(void);
const char *__asan_get_report_description(void);
const char *__asan_locate_address(void *addr, char *name, SIZE_T name_size, void **region_address,
        SIZE_T *region_size);
SIZE_T __asan_get_alloc_stack(void *addr, void **trace, SIZE_T size, int *thread_id);
SIZE_T __asan_get_free_stack(void *addr, void **trace, SIZE_T size, int *thread_id);
void __asan_get_shadow_mapping(SIZE_T *shadow_scale, SIZE_T *shadow_offset);
void __asan_report_error(void *pc, void *bp, void *sp, void *addr, int is_write, SIZE_T access_size);
void __asan_set_death_callback(void (*callback)(void));
void __asan_set_error_report_callback(void (*callback)(const char *));
void __asan_on_error(void);
void __asan_print_accumulated_stats(void);
const char *__asan_default_options(void);
void *__asan_get_current_fake_stack(void);
void *__asan_addr_is_in_fake_stack(void *fake_stack, void *addr, void **beg, void **end);
void __asan_handle_no_return(void);
int __asan_update_allocation_context(void *addr);

/* Internal APIs */
void __asan_init(void);
ULONG_PTR __asan_get_shadow_memory_dynamic_address(void);
int __asan_should_detect_stack_use_after_return(void);
void __asan_version_mismatch_check_v8(void);
void __asan_register_image_globals(ULONG_PTR *flag);
void __asan_unregister_image_globals(ULONG_PTR *flag);
void __asan_register_elf_globals(ULONG_PTR *flag, void *start, void *stop);
void __asan_unregister_elf_globals(ULONG_PTR *flag, void *start, void *stop);
void __asan_register_globals(void *globals, ULONG_PTR n);
void __asan_unregister_globals(void *globals, ULONG_PTR n);
void __asan_before_dynamic_init(const void *name);
void __asan_after_dynamic_init(void);
void __asan_set_shadow_00(const void *addr, SIZE_T size);
void __asan_set_shadow_01(const void *addr, SIZE_T size);
void __asan_set_shadow_02(const void *addr, SIZE_T size);
void __asan_set_shadow_03(const void *addr, SIZE_T size);
void __asan_set_shadow_04(const void *addr, SIZE_T size);
void __asan_set_shadow_05(const void *addr, SIZE_T size);
void __asan_set_shadow_06(const void *addr, SIZE_T size);
void __asan_set_shadow_07(const void *addr, SIZE_T size);
void __asan_set_shadow_f1(const void *addr, SIZE_T size);
void __asan_set_shadow_f2(const void *addr, SIZE_T size);
void __asan_set_shadow_f3(const void *addr, SIZE_T size);
void __asan_set_shadow_f5(const void *addr, SIZE_T size);
void __asan_set_shadow_f8(const void *addr, SIZE_T size);
void __asan_stack_free_0(void *, SIZE_T size);
void __asan_stack_free_1(void *, SIZE_T size);
void __asan_stack_free_2(void *, SIZE_T size);
void __asan_stack_free_3(void *, SIZE_T size);
void __asan_stack_free_4(void *, SIZE_T size);
void __asan_stack_free_5(void *, SIZE_T size);
void __asan_stack_free_6(void *, SIZE_T size);
void __asan_stack_free_7(void *, SIZE_T size);
void __asan_stack_free_8(void *, SIZE_T size);
void __asan_stack_free_9(void *, SIZE_T size);
void __asan_stack_free_10(void *, SIZE_T size);
void *__asan_stack_malloc_0(SIZE_T size);
void *__asan_stack_malloc_1(SIZE_T size);
void *__asan_stack_malloc_2(SIZE_T size);
void *__asan_stack_malloc_3(SIZE_T size);
void *__asan_stack_malloc_4(SIZE_T size);
void *__asan_stack_malloc_5(SIZE_T size);
void *__asan_stack_malloc_6(SIZE_T size);
void *__asan_stack_malloc_7(SIZE_T size);
void *__asan_stack_malloc_8(SIZE_T size);
void *__asan_stack_malloc_9(SIZE_T size);
void *__asan_stack_malloc_10(SIZE_T size);
void *__asan_stack_malloc_always_0(SIZE_T size);
void *__asan_stack_malloc_always_1(SIZE_T size);
void *__asan_stack_malloc_always_2(SIZE_T size);
void *__asan_stack_malloc_always_3(SIZE_T size);
void *__asan_stack_malloc_always_4(SIZE_T size);
void *__asan_stack_malloc_always_5(SIZE_T size);
void *__asan_stack_malloc_always_6(SIZE_T size);
void *__asan_stack_malloc_always_7(SIZE_T size);
void *__asan_stack_malloc_always_8(SIZE_T size);
void *__asan_stack_malloc_always_9(SIZE_T size);
void *__asan_stack_malloc_always_10(SIZE_T size);
void __asan_load1(void *p);
void __asan_load2(void *p);
void __asan_load4(void *p);
void __asan_load8(void *p);
void __asan_load16(void *p);
void __asan_store1(void *p);
void __asan_store2(void *p);
void __asan_store4(void *p);
void __asan_store8(void *p);
void __asan_store16(void *p);
void __asan_loadN(void *p, SIZE_T size);
void __asan_storeN(void *p, SIZE_T size);
void __asan_load1_noabort(void *p);
void __asan_load2_noabort(void *p);
void __asan_load4_noabort(void *p);
void __asan_load8_noabort(void *p);
void __asan_load16_noabort(void *p);
void __asan_store1_noabort(void *p);
void __asan_store2_noabort(void *p);
void __asan_store4_noabort(void *p);
void __asan_store8_noabort(void *p);
void __asan_store16_noabort(void *p);
void __asan_loadN_noabort(void *p, SIZE_T size);
void __asan_storeN_noabort(void *p, SIZE_T size);
void DECLSPEC_NORETURN __asan_report_load1(void *p);
void DECLSPEC_NORETURN __asan_report_load2(void *p);
void DECLSPEC_NORETURN __asan_report_load4(void *p);
void DECLSPEC_NORETURN __asan_report_load8(void *p);
void DECLSPEC_NORETURN __asan_report_load16(void *p);
void DECLSPEC_NORETURN __asan_report_store1(void *p);
void DECLSPEC_NORETURN __asan_report_store2(void *p);
void DECLSPEC_NORETURN __asan_report_store4(void *p);
void DECLSPEC_NORETURN __asan_report_store8(void *p);
void DECLSPEC_NORETURN __asan_report_store16(void *p);
void __asan_report_load_n(void *p, SIZE_T size);
void __asan_report_store_n(void *p, SIZE_T size);
void __asan_report_load1_noabort(void *p);
void __asan_report_load2_noabort(void *p);
void __asan_report_load4_noabort(void *p);
void __asan_report_load8_noabort(void *p);
void __asan_report_load16_noabort(void *p);
void __asan_report_store1_noabort(void *p);
void __asan_report_store2_noabort(void *p);
void __asan_report_store4_noabort(void *p);
void __asan_report_store8_noabort(void *p);
void __asan_report_store16_noabort(void *p);
void __asan_report_load_n_noabort(void *p, SIZE_T size);
void __asan_report_store_n_noabort(void *p, SIZE_T size);
void __asan_exp_load1(void *p, UINT32 exp);
void __asan_exp_load2(void *p, UINT32 exp);
void __asan_exp_load4(void *p, UINT32 exp);
void __asan_exp_load8(void *p, UINT32 exp);
void __asan_exp_load16(void *p, UINT32 exp);
void __asan_exp_store1(void *p, UINT32 exp);
void __asan_exp_store2(void *p, UINT32 exp);
void __asan_exp_store4(void *p, UINT32 exp);
void __asan_exp_store8(void *p, UINT32 exp);
void __asan_exp_store16(void *p, UINT32 exp);
void __asan_exp_loadN(void *p, SIZE_T size, UINT32 exp);
void __asan_exp_storeN(void *p, SIZE_T size, UINT32 exp);
void *__asan_memcpy(void *dst, const void *src, ULONG_PTR size);
void *__asan_memset(void *s, int c, ULONG_PTR n);
void *__asan_memmove(void *dest, const void *src, ULONG_PTR n);
void __asan_poison_cxx_array_cookie(ULONG_PTR p);
ULONG_PTR __asan_load_cxx_array_cookie(ULONG_PTR *p);
void __asan_poison_intra_object_redzone(ULONG_PTR p, ULONG_PTR size);
void __asan_unpoison_intra_object_redzone(ULONG_PTR p, ULONG_PTR size);
void __asan_alloca_poison(void *addr, SIZE_T size);
void __asan_allocas_unpoison(void *top, SIZE_T bottom);
const char *__asan_default_suppressions(void);
void __asan_handle_vfork(void *sp);

struct wine_asan_funcs
{
    void (*p___asan_poison_memory_region)(void const volatile *addr, SIZE_T size);
    void (*p___asan_unpoison_memory_region)(void const volatile *addr, SIZE_T size);
    void (*p___asan_poison_stack_memory)(void const volatile *addr, SIZE_T size);
    void (*p___asan_unpoison_stack_memory)(void const volatile *addr, SIZE_T size);
    int (*p___asan_address_is_poisoned)(void const volatile *addr);
    void *(*p___asan_region_is_poisoned)(void *beg, SIZE_T size);
    void (*p___asan_describe_address)(void *addr);
    int (*p___asan_report_present)(void);
    void *(*p___asan_get_report_pc)(void);
    void *(*p___asan_get_report_bp)(void);
    void *(*p___asan_get_report_sp)(void);
    void *(*p___asan_get_report_address)(void);
    int (*p___asan_get_report_access_type)(void);
    SIZE_T (*p___asan_get_report_access_size)(void);
    const char *(*p___asan_get_report_description)(void);
    const char *(*p___asan_locate_address)(void *addr, char *name, SIZE_T name_size,
            void **region_address, SIZE_T *region_size);
    SIZE_T (*p___asan_get_alloc_stack)(void *addr, void **trace, SIZE_T size, int *thread_id);
    SIZE_T (*p___asan_get_free_stack)(void *addr, void **trace, SIZE_T size, int *thread_id);
    void (*p___asan_get_shadow_mapping)(SIZE_T *shadow_scale, SIZE_T *shadow_offset);
    void (*p___asan_report_error)(void *pc, void *bp, void *sp, void *addr, int is_write, SIZE_T access_size);
    void (*p___asan_set_death_callback)(void (*callback)(void));
    void (*p___asan_set_error_report_callback)(void (*callback)(const char *));
    void (*p___asan_on_error)(void);
    void (*p___asan_print_accumulated_stats)(void);
    const char *(*p___asan_default_options)(void);
    void *(*p___asan_get_current_fake_stack)(void);
    void *(*p___asan_addr_is_in_fake_stack)(void *fake_stack, void *addr, void **beg, void **end);
    void (*p___asan_handle_no_return)(void);
    int (*p___asan_update_allocation_context)(void *addr);

    void (*p___asan_init)(void);
    ULONG_PTR (*p___asan_get_shadow_memory_dynamic_address)(void);
    int (*p___asan_should_detect_stack_use_after_return)(void);
    void (*p___asan_version_mismatch_check_v8)(void);
    void (*p___asan_register_image_globals)(ULONG_PTR *flag);
    void (*p___asan_unregister_image_globals)(ULONG_PTR *flag);
    void (*p___asan_register_elf_globals)(ULONG_PTR *flag, void *start, void *stop);
    void (*p___asan_unregister_elf_globals)(ULONG_PTR *flag, void *start, void *stop);
    void (*p___asan_register_globals)(void *globals, ULONG_PTR n);
    void (*p___asan_unregister_globals)(void *globals, ULONG_PTR n);
    void (*p___asan_before_dynamic_init)(const void *name);
    void (*p___asan_after_dynamic_init)(void);
    void (*p___asan_set_shadow_00)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_01)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_02)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_03)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_04)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_05)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_06)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_07)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_f1)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_f2)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_f3)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_f5)(const void *addr, SIZE_T size);
    void (*p___asan_set_shadow_f8)(const void *addr, SIZE_T size);
    void (*p___asan_stack_free_0)(void *, SIZE_T size);
    void (*p___asan_stack_free_1)(void *, SIZE_T size);
    void (*p___asan_stack_free_2)(void *, SIZE_T size);
    void (*p___asan_stack_free_3)(void *, SIZE_T size);
    void (*p___asan_stack_free_4)(void *, SIZE_T size);
    void (*p___asan_stack_free_5)(void *, SIZE_T size);
    void (*p___asan_stack_free_6)(void *, SIZE_T size);
    void (*p___asan_stack_free_7)(void *, SIZE_T size);
    void (*p___asan_stack_free_8)(void *, SIZE_T size);
    void (*p___asan_stack_free_9)(void *, SIZE_T size);
    void (*p___asan_stack_free_10)(void *, SIZE_T size);
    void *(*p___asan_stack_malloc_0)(SIZE_T size);
    void *(*p___asan_stack_malloc_1)(SIZE_T size);
    void *(*p___asan_stack_malloc_2)(SIZE_T size);
    void *(*p___asan_stack_malloc_3)(SIZE_T size);
    void *(*p___asan_stack_malloc_4)(SIZE_T size);
    void *(*p___asan_stack_malloc_5)(SIZE_T size);
    void *(*p___asan_stack_malloc_6)(SIZE_T size);
    void *(*p___asan_stack_malloc_7)(SIZE_T size);
    void *(*p___asan_stack_malloc_8)(SIZE_T size);
    void *(*p___asan_stack_malloc_9)(SIZE_T size);
    void *(*p___asan_stack_malloc_10)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_0)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_1)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_2)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_3)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_4)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_5)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_6)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_7)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_8)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_9)(SIZE_T size);
    void *(*p___asan_stack_malloc_always_10)(SIZE_T size);
    void (*p___asan_load1)(void *p);
    void (*p___asan_load2)(void *p);
    void (*p___asan_load4)(void *p);
    void (*p___asan_load8)(void *p);
    void (*p___asan_load16)(void *p);
    void (*p___asan_store1)(void *p);
    void (*p___asan_store2)(void *p);
    void (*p___asan_store4)(void *p);
    void (*p___asan_store8)(void *p);
    void (*p___asan_store16)(void *p);
    void (*p___asan_loadN)(void *p, SIZE_T size);
    void (*p___asan_storeN)(void *p, SIZE_T size);
    void (*p___asan_load1_noabort)(void *p);
    void (*p___asan_load2_noabort)(void *p);
    void (*p___asan_load4_noabort)(void *p);
    void (*p___asan_load8_noabort)(void *p);
    void (*p___asan_load16_noabort)(void *p);
    void (*p___asan_store1_noabort)(void *p);
    void (*p___asan_store2_noabort)(void *p);
    void (*p___asan_store4_noabort)(void *p);
    void (*p___asan_store8_noabort)(void *p);
    void (*p___asan_store16_noabort)(void *p);
    void (*p___asan_loadN_noabort)(void *p, SIZE_T size);
    void (*p___asan_storeN_noabort)(void *p, SIZE_T size);
    void DECLSPEC_NORETURN (*p___asan_report_load1)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_load2)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_load4)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_load8)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_load16)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_store1)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_store2)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_store4)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_store8)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_store16)(void *p);
    void DECLSPEC_NORETURN (*p___asan_report_load_n)(void *p, SIZE_T size);
    void DECLSPEC_NORETURN (*p___asan_report_store_n)(void *p, SIZE_T size);
    void (*p___asan_report_load1_noabort)(void *p);
    void (*p___asan_report_load2_noabort)(void *p);
    void (*p___asan_report_load4_noabort)(void *p);
    void (*p___asan_report_load8_noabort)(void *p);
    void (*p___asan_report_load16_noabort)(void *p);
    void (*p___asan_report_store1_noabort)(void *p);
    void (*p___asan_report_store2_noabort)(void *p);
    void (*p___asan_report_store4_noabort)(void *p);
    void (*p___asan_report_store8_noabort)(void *p);
    void (*p___asan_report_store16_noabort)(void *p);
    void (*p___asan_report_load_n_noabort)(void *p, SIZE_T size);
    void (*p___asan_report_store_n_noabort)(void *p, SIZE_T size);
    void (*p___asan_exp_load1)(void *p, UINT32 exp);
    void (*p___asan_exp_load2)(void *p, UINT32 exp);
    void (*p___asan_exp_load4)(void *p, UINT32 exp);
    void (*p___asan_exp_load8)(void *p, UINT32 exp);
    void (*p___asan_exp_load16)(void *p, UINT32 exp);
    void (*p___asan_exp_store1)(void *p, UINT32 exp);
    void (*p___asan_exp_store2)(void *p, UINT32 exp);
    void (*p___asan_exp_store4)(void *p, UINT32 exp);
    void (*p___asan_exp_store8)(void *p, UINT32 exp);
    void (*p___asan_exp_store16)(void *p, UINT32 exp);
    void (*p___asan_exp_loadN)(void *p, SIZE_T size, UINT32 exp);
    void (*p___asan_exp_storeN)(void *p, SIZE_T size, UINT32 exp);
    void *(*p___asan_memcpy)(void *dst, const void *src, ULONG_PTR size);
    void *(*p___asan_memset)(void *s, int c, ULONG_PTR n);
    void *(*p___asan_memmove)(void *dest, const void *src, ULONG_PTR n);
    void (*p___asan_poison_cxx_array_cookie)(ULONG_PTR p);
    ULONG_PTR (*p___asan_load_cxx_array_cookie)(ULONG_PTR *p);
    void (*p___asan_poison_intra_object_redzone)(ULONG_PTR p, ULONG_PTR size);
    void (*p___asan_unpoison_intra_object_redzone)(ULONG_PTR p, ULONG_PTR size);
    void (*p___asan_alloca_poison)(void *addr, SIZE_T size);
    void (*p___asan_allocas_unpoison)(void *top, SIZE_T bottom);
    const char *(*p___asan_default_suppressions)(void);
    void (*p___asan_handle_vfork)(void *sp);
};

extern ULONG_PTR __asan_shadow_memory_dynamic_address;
extern int __asan_option_detect_stack_use_after_return;
#endif
