/*
 * IDL Compiler
 *
 * Copyright 2002 Ove Kaaven
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#include "config.h"

#include <stdarg.h>
#include <stdio.h>

#include "widl.h"
#include "utils.h"
#include "parser.h"
#include "header.h"
#include "expr.h"
#include "typetree.h"
#include "typelib.h"

static int indent;

static void write_import( const char *import )
{
    char *header = replace_extension( get_basename( import ), ".idl", ".h" );
    put_str( indent, "#include <%s>\n", header );
    free( header );
}

static void write_imports( const statement_list_t *stmts )
{
    const statement_t *stmt;

    if (stmts) LIST_FOR_EACH_ENTRY( stmt, stmts, const statement_t, entry )
    {
        switch (stmt->type)
        {
        case STMT_IMPORT: write_import( stmt->u.str ); break;
        case STMT_LIBRARY: write_imports( stmt->u.lib->stmts ); break;
        case STMT_TYPE:
            if (type_get_type( stmt->u.type ) != TYPE_INTERFACE) break;
            write_imports( type_iface_get_stmts( stmt->u.type ) );
            break;
        default: break;
        }
    }
}

void write_comimpl( const statement_list_t *stmts )
{
    if (!do_comimpl) return;

    init_output_buffer();
    put_str( indent, "/*** Autogenerated by WIDL %s from %s - Do not edit ***/\n\n", PACKAGE_VERSION, input_name );
    write_imports( stmts );
    put_str( indent, "\n" );

    flush_output_buffer( comimpl_name );
}
